### ISSUE TITLE
Feature settings

### ISSUE THREAD

**Issue by tmcdon89** [WISPBill/WISPBill-Web-App#3]
I think it would be handy to add some features for radius integrations as well as provisioning etc ... Once the core is built up. Do you have a preference on making a settings table or config files?

**Comment by turtles2** [comment]
The last version I used a config file but I felt that was sloppy. I am thinking a table would be cleaner and make managing easier. What do you think?

**Comment by tmcdon89** [comment]
My preference would be a settings table. Then new settings for a feature can be added to the table with a simple migration file at that point. It makes for a robust clean setup in my opinion. The table could be as simple as -setting name -default value -current value

**Comment by tmcdon89** [comment]
Being in a table gives the additional benefit of easily turning settings and features on or off from within the app.

**Comment by turtles2** [comment]
I agree that would be the best way. I believe this is resolved so I am going to close it.

**Comment by turtles2** [comment]
I did't see a use for a default value. So I left it out.

**Comment by tmcdon89** [comment]
The only reason for a default value would be so the user could set something back to a value that "should" work. It just shows them what they changed. It's definitely not necessary in the context of a true use. Mostly just a reference. But we could easily document what the default values are in a seed file or the wiki.
