### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by tmcdon89** [WISPBill/WISPBill-Web-App#4]
I'm not sure if you've considered something such as the following to make forms easier:
https://laravelcollective.com/docs/5.1/html
Just wanted to put it out there as an option since you might not already be familiar with it.

On a side note if there is something in particular you'd like for me to work on to contribute with I'd be happy to help. Currently I'm just monitoring what you're adding to get a feel for how you're envisioning it.

**Comment by turtles2** [comment]
Honestly I have not even given it any thought. What I have been thinking about most is how to do the customer portal I have been flip flopping between a separate application that uses an API or using middleware and the like. Perhaps you have some thoughts to help sway me one way or the other. 

In terms of contributing you could look at adding plans. It needs to work with stripe. Stripe is a great API with awesome docs so if you have never used it you can get up to speed fast. The way I envision it working is a controller whose sole job is to work with payment gateways that way we can add others later. I looked for some package but could not find any that fit well. As I need customers to have more then one plan. 

FYI I am using the most up to date stripe API.

**Comment by tmcdon89** [comment]
I think that doing the customer portal with middleware is a good solution. In my opinion the customer facing side of the project is more of a second phase. Its more important that the administrative features function well than it is for a customer to see anything besides bill paying options to start with.  As far as splitting the customer portal out I think it will only be worth it to split out the customer functions if it gets too bloated in the app, but I would imagine that's a long way off. 

On a side note, The registration form currently allows to select admin status I'm assuming this is temporary during initial development? It also requires a user image and phone number, it shouldn't be hard to assign a default image if none is chosen and I'm just curious if the phone number is necessary for staff etc...? Thoughts?

**Comment by turtles2** [comment]
I am not concerned about building the portal I just want to lay a strong foundation for it so that things don't have to be redone. 

Yes I plan to remove that and allow admins to promote nonadmins. A default image would be very doable. As for the phone number I see it as a need for staff but we could make it optional.

**Comment by tmcdon89** [comment]
I think that going the middleware route will be plenty sufficient then especially considering with the billing APIs most truly "sensitive" information can be stored offsite.

**Comment by turtles2** [comment]
I don't see why this needs to stay open therefore I am closing it.
