### ISSUE TITLE
Discussion/Questions

### ISSUE THREAD

**Issue by tmcdon89** [WISPBill/WISPBill-Web-App#5]
I'm opening this issue as a place to have a discussion on various things that may not require their own "Issue" per say. 

For instance:
What was your reasoning behind the customer_info table? Are these purely leads and "users" will be active subscriptions and admins etc...? Or will there likely be another table for customers?

**Comment by turtles2** [comment]
It is to store leads and customers. I see the difference between leads and customers to be done by an active billing set up. I see one customer having more than one user account as many of my business clients want multiple people to be able to access there billing and support functions over the phone and  on a portal from my talking to them.

**Comment by tmcdon89** [comment]
I'm gearing up to start submitting some commits for packages. Before I start though, do you have anything against a "Models" folder within the "app" folder. I generally leave the "User" model in the app folder but everything else into the "Models" folder for cleanliness and it follows the pattern of the folder structure in general. I end up leaving the User model out simply because some packages are built to reference it in its default location.

**Comment by turtles2** [comment]
I did not know you could do that. I thought all had to be in App.  But if that is not the case I have no problem with it, in fact I would prefer a folder.

**Comment by tmcdon89** [comment]
Yah it just requires that you update the namespace to App\Models*whatever*
The same applies when you are referencing it from controllers as well.

**Comment by tmcdon89** [comment]
I haven't skimmed all the way through the code on the leads yet but I'm not getting my geo markers created in the customer locations table. Is that supposed to be working yet, or just in place?

**Comment by turtles2** [comment]
Did you configure the mapzen geocoder? If you did not it should throw an error? Also Mapzen is based on [OpenAddress ](https://openaddresses.io/) data so if your area dose not have data it will throw lat/lang that are way off. You may want to have your areas data included

**Comment by tmcdon89** [comment]
It looks like that may be the issue. I have the Mapzen api key etc... but looking at the OpenAddress map there isn't much info for rural Tennessee which is where we are located.

**Comment by turtles2** [comment]
I suggest contacting your county some offer said data for free. You can then open an issue on there github and they will pull it in.

**Comment by tmcdon89** [comment]
Conflicts - 
In order to avoid conflicts while we're both working do you want me to avoid the primary files such as the sidebar and routes? Everything else shouldn't make a lot of conflicts if we are both publishing edits.

**Comment by turtles2** [comment]
Sounds good but make sure to tell me what changes are needed to them.

**Comment by turtles2** [comment]
@tmcdon89 Can you let me know what you are working on right now (I assume you are because you are pulling my commits in)? I want to avoid duplicating anything. I am going to work on 2 openadrress geocoder workarounds. The US Census which has good US wide residential coverage and manual based on dropping a pin.

**Comment by tmcdon89** [comment]
I'm currently at a standstill, but the only thing I've done work for up to this point is for packages.

**Comment by turtles2** [comment]
OK good to know.

**Comment by turtles2** [comment]
FYI if you make any controllers going forward use must call this after auth middleware  $this->middleware('role'); it checks if the user is role "No Access" That is the default role from the Register page if there are users. If there are no users the default role is admin.

**Comment by tmcdon89** [comment]
So I don't have much experience with the openaddress capabilities. I'm wondering if there would be a way to pull all addresses within the given confines of a tower site. So if a circle geometry was drawn, could you get all of the mailing addresses available within that circle so that mailers could be sent out efficiently when a new tower is going up.

**Comment by turtles2** [comment]
OpenAddress is just a data-set like OpenStreet Map is. Mapzen use's that data-set to power a geocoder which WISPBill makes API calls to. To do what your asking would require a machine with the data-set that then takes said data-set and analyzes for all points in said area. There are a few ways to do such and it sounds like a cool use of the data. But I feel that amount of calculating is beyond PHP (I will double check with research) and more suited for python or some other language. 

This idea intrigues me allot my thoughts right now are that it would probably need to be external service that WISPBill calls like Mapzen. Don't quote me on this but I want to try to get a experimental system up and running shortly.

**Comment by turtles2** [comment]
Scratch what I said. It can be done with PostGis in SQL.

**Comment by tmcdon89** [comment]
Awesome

**Comment by turtles2** [comment]
My thoughts are that I set it up as an API (I will publish the file that runs it). As the OpenAddress Data-Set is about 3.3 GB and growing right now. I have a dev server that is always on. I could route the calls over my domain. It takes a little work to set up PostGis and Import OpenAddress. So I don't see why we both would have to do it. Obliviously production is a different story.

**Comment by turtles2** [comment]
FYI even the US data-set is expanding to over 100 GB in the DB. I am only going to import MN and TN into the DB.

**Comment by turtles2** [comment]
Even MN and TN took up about 50 GB. It took over 6 hours to return a result. I am going to abandon  postgis. I am going to make a system in Python that loads and searches the CSVs as needed.

**Comment by turtles2** [comment]
If you want you can use http://wispbill.oaknetwireless.com for the Address URL. My Data-Set has MN and TN data. You can also go to [This Repo for the underlying code](https://github.com/WISPBill/Open-Mail-Marketing)

**Comment by turtles2** [comment]
When ever you get time please let me know how it works. It did my area in about 30 Secs.

**Comment by tmcdon89** [comment]
I seem to be doing something wrong in the site creation phase.
I am able to place a site but I can't get the site to keep a shape for the coverage area.

**Comment by turtles2** [comment]
Are you closing the shape by selecting the first point? Are you able to
even draw it?

**Comment by turtles2** [comment]
Thought you may want to know my server is Intel Pentium 4 CPU 3.00GHz, 2 cores with 2 GB of ram. So a bigger server would be much faster.

**Comment by tmcdon89** [comment]
The shape draws out and I am closing it. But when I select to save its gone when the page reloads.

**Comment by turtles2** [comment]
JavaScript is not my strong suit. Coverage for a site is only loaded on the site when you double click to edit. It was the only way to be able to edit coverage without having to make it more complicated. If you pull down the latest commit you can view coverage on a different page.

**Comment by turtles2** [comment]
Did you ever get it working? I am curious if you tried the address getter?

**Comment by tmcdon89** [comment]
Its been awhile since I've had time to take a look. I'll see if its going with the latest revisions and let you know.

**Comment by tmcdon89** [comment]
Ok, finally got a chance to do a clean install and try it out again. I'm now seeing the coverage map saved. So thats awesome. I'm not currently getting any addresses returned. It looks like I'm currently getting an error 500 returned when I attempt the address retrieval.

**Comment by turtles2** [comment]
Did you reconfigure the end point in settings? As that is for testing
purposes so I didn't put it in the seeder. The server should timeout on my
end if it takes over 290 secs.

**Comment by turtles2** [comment]
I just add some time to run some tests it appears to be a DNS issue with my subdomain forwarding. I will let you know when it is resolved.

**Comment by turtles2** [comment]
Please pull down the latest commit it has the fix. The issue was curl was not following the 302 redirect on the subdomain to my server.

**Comment by tmcdon89** [comment]
That did it. Nice work.
